### ISSUE TITLE
poeninja API endpoint changed

### ISSUE THREAD

**Issue by bferrantino** [aRTy42/POE-ItemInfo#100]
on line 10515 of the POE-ItemInfo.ahk file, the API endpoint for currency rates is incorrect. I have changed locally and it seems to be working now, but I cannot commit my changes. Please update the master to have the following change:

Change line 10515:
FROM : http://poeninja.azureedge.net/api
TO : http://poe.ninja/api

**Comment by Eruyome** [comment]
Fixed in TradeMacro, sooner or later those changes will be added here.

**Comment by bferrantino** [comment]
yes, i saw this was updated correctly in TradeMacro. I have actually started using that instead. but it would be good to keep them in sync :)

**Comment by Eruyome** [comment]
We do, but there will be bigger changes soon anyway that have to be synched and I guess most people use TradeMacro instead of the standalone ItemInfo. So while it may be implemented really soon in ItemInfo, I'm not sure if aRTy wants to make a release for it.
