### ISSUE TITLE
New Item Mods - unknown mod

### ISSUE THREAD

**Issue by miaXcova** [aRTy42/POE-ItemInfo#110]
Some mods on new items such as Shaper, Elder, and Eye Jewels show up as 'unknown mod'

AHK version: 1.1.26.01
Windows version: 10 Home

Item Info version: 3.0.06-beta (updated today with TradeMacro)
TradeMacro version:  v2.7.2

**Comment by aRTy42** [comment]
There is a new ItemInfo version for a few days, but it is not included in the TradeMacro yet. I'm not sure why Eruyome didn't do another TradeMacro release, he might be otherwise busy due to the holidays.

**Comment by miaXcova** [comment]
For the meantime until Eruyome gets back after the holidays, I downloaded and extracted your current build to a new directory and ran it _after_ running TradeMacro.  It acts a little funky when checking prices, meaning it opens an item info window then opens the price window on top of it.  This is not entirely undesirable, since the item info window opens immediately while the price window takes a few more seconds.  When both mods are finally updated, this is an unintended feature I will end up missing.

Anyway, thanks for the update.  It does fix a lot of missing data, but there are still items that are showing up with unknown mods.  In particular many (but not all) of the `+# to maximum life` on eyeball jewels.

**Comment by aRTy42** [comment]
The life mods are completely fine with all the eyeball jewels I have. Eruyome merged my pull request of the ItemInfo update now but didn't create a release. You could download the current master version (permalink [here](https://github.com/PoE-TradeMacro/POE-TradeMacro/tree/5239a23401794cb7bcc80f80ca83fce7f5bf4d24)). You should use a new directory for that one aswell. There will be a few extra files, but you can simply use the "Run_TradeMacro" as usual (and only that).

**Comment by aRTy42** [comment]
Thanks for bringing up jewels though, confirming that the life mod works on my end led to four mods that didn't work or were still missing, but are fixed locally now.

**Comment by miaXcova** [comment]
I think maps are still not updated.  The maps themselves are ok, but the paths and upgrade from/to are still the old values prior to War for Atlas.

**Comment by aRTy42** [comment]
Correct, the tooltip should say it's the "OLD 3.0 INFORMATION"
Map info scraping from the wiki wasn't possible yet and the jewels seemed more important to do. Shaper/Elder mods and maps will likely follow within the next week, or two.

**Comment by miaXcova** [comment]
When are we going to get current map info like we had before?  You know, the `upgrades from 3 this map`, and `upgrades to this map`, as well as boss arena or no boss arena.  This information is extremely valuable especially when speed running through maps for the atlas tick to know if you got the boss.  With 157 maps this league it's near impossible to remember which has a proper boss arena.

**Comment by aRTy42** [comment]
The whole preparation worked out quite different than I expected. I don't have boss descriptions for the new maps yet, but the factual 3->1 upgrade info is done and boss arenas are comparibly easy. I think I'll have a new version ready without boss descriptions in the next days.

**Comment by aRTy42** [comment]
Released an update for maps/uniques/divination cards, including map boss descriptions. Gave Eru a branch with the updates for the TradeMacro, should be in once he got time/patience.

**Comment by Eruyome** [comment]
Should be in now. Not released yet though.
