### ISSUE TITLE
Search Opal Ring with ilvl by default

### ISSUE THREAD

**Issue by C485** [aRTy42/POE-ItemInfo#111]
Ctrl+D shows wrong price for Opal Ring, ilvl: 84 shows price around 15 chaos with should be 35chaos +-
Imho script should check price directly on poe.trade not in poeprice

**Comment by aRTy42** [comment]
That's about the [TradeMacro](https://github.com/PoE-TradeMacro/POE-TradeMacro/issues), please post it there.
