### ISSUE TITLE
SendCtrlC

### ISSUE THREAD

**Issue by SirNorek** [aRTy42/POE-ItemInfo#113]
Hey there, not sure if anyone else is running into this, but I checked the faq and issues and saw nothing.

My script is running elevated (as per default) everything else works 100%, but the send CTRL C function (default binding is CTRL Rclick, which is what I want) tried changing it to CTRL ALT Rclick just to test, still no dice.

**Comment by aRTy42** [comment]
So using Ctrl+C itself works but using Ctrl+Rclick to send it does not?

Just to be sure: You ticked the box in the additional macros settings and restarted the script?

**Comment by SirNorek** [comment]
Correct, Ctrl+C and every other shortcut I've tried works (cD cQ caD etc etc) but cRclick does nothing.

It is enabled, I reloaded the script (my PC has been restarted since then also) and nothing happens. This is also the only script I currently have running on AHK.

 Wanted to use it to post my buying message, or repost when making groups etc, but no matter what I have copied in my clipboard nothing gets posted in chat

**Comment by aRTy42** [comment]
What exactly are you trying to do?

The function was meant for people who dislike pressing Ctrl+C on items because it does not suit their hand placement, so these people can use Ctrl+Rclick to get the ItemInfo tooltip.

**Comment by SirNorek** [comment]
Oh wow... I guess the wording threw me off >.> "Send CtrlC" to me sounded like sending your clipboard to chat, since this is a trade script I thought this was a convenience function for sending buy messages etc.

On that note, would be a nice addition :P
