### ISSUE TITLE
Don't remove clipboard contents

### ISSUE THREAD

**Issue by Krzysiu** [aRTy42/POE-ItemInfo#120]
The script deletes clipboard contents when the content is not a raw text. It's because number of lines like
`ClipBoardTemp := Clipboard`

where the proper way<sup>[1]</sup> to save clipboard is:
`ClipBoardTemp := ClipboardAll`

<sup>[1] https://autohotkey.com/docs/misc/Clipboard.htm#ClipboardAll</sup>

**Comment by Eruyome** [comment]
I have replaced those line with ClipBoardAll (dev version, will be released in a while).
