### ISSUE TITLE
Can't create control error

### ISSUE THREAD

**Issue by Sindusk** [aRTy42/POE-ItemInfo#124]
Script will not load. Downloaded latest version of AutoHotkey and running script as administrator.

https://i.imgur.com/H5gqJji.png

**Comment by aRTy42** [comment]
I'm not sure what the problem is, but you can try to delete your user-setting files in case some old stuff causes issues. You should find several .ini files at `<Documents>\PoE-ItemInfo`

**Comment by Sindusk** [comment]
Seems like it was a conflict of some kind. I deleted the folder you mentioned, it still came up with the error. Restarted my computer and it is now working.
