### ISSUE TITLE
[Feature Request] Update MapList.txt for 3.6.0

### ISSUE THREAD

**Issue by temmings** [aRTy42/POE-ItemInfo#125]
Hi, POE-ItemInfo is good tool. :)
However, the contents of "MapList.txt" do not seem to match the current 3.6.0.

I tried to support 3.6.0.
- [3.6.0 MapData Wiki (WIP)](https://pathofexile.gamepedia.com/User:Temmings/MapData)
- [change: scrape_poe_maps.py](https://github.com/temmings/scrape_poe_info/commit/506ee8cfdefe8e06a6b50ba54cc66a9e5be96255)
- [generated MapList.txt](https://gist.github.com/temmings/78ad02273138f2f0d895261fe1e2170e)

Would you like to update the wiki "[User: ARTyficial / MapData](https://pathofexile.gamepedia.com/User:ARTyficial/MapData)" to [the 3.6.0 based content](https://pathofexile.gamepedia.com/User:Temmings/MapData) I created? If you agree.

**Comment by aRTy42** [comment]
I rewrote the map scraping script to make use of the wiki API, this means the wiki user page will no longer be necessary. I'll upload the new script soon. The map list will be updated before legion league to catch up with the synthesis changes and then again a few days into legion league to hopefully cover the atlas layout.
