### ISSUE TITLE
is this normal?

### ISSUE THREAD

**Issue by Maldrog** [aRTy42/POE-ItemInfo#127]
after getting my trade macro up, my AVG says that this is a threat : POE-TradeMacro-2.14.1\resources\ahk\Merge_TradeMacro.ahk, my pc started lagging hard so it was kinda hard to click white list, so ye, wanted to check here if i did the right thing. or did i somehow do something wrong with the insallation, thanks for any answers i can get. by the way i'm kinda dumb at pc:)

**Comment by aRTy42** [comment]
Hi, the TradeMacro project is [here](https://github.com/PoE-TradeMacro/POE-TradeMacro/issues). Getting a threat warning from AVG is a known problem, anti-virus programs seem to dislike ahk-scripts launching each other (see [here](https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/943) for example).

I don't know whether the lagging is normal. If it just happened while the AVG popped up and the macro runs fine now, then I would not worry about it. If it still lags, then you might need to look into it. The only other report I could quickly find was [this](https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/832) and that one was a rather specific issue from that user.

**Comment by Maldrog** [comment]
okay i see, thanks for the help:)
