### ISSUE TITLE
No rare estimate

### ISSUE THREAD

**Issue by IMakeRoguelikes** [aRTy42/POE-ItemInfo#137]
When I press the price check keybind (Ctrl + D) On a identified rare item it gets stuck on "Getting price prediction..." Then after a while it gives me "Error 504: PoePrices api is under load or is down"

**Comment by aRTy42** [comment]
I don't maintain this project anymore. The price check is a feature of the [PoE-TradeMacro](https://github.com/PoE-TradeMacro/POE-TradeMacro) which was built based on this tool, but it is another project. It does not look like it is getting updated either anymore though.
