### ISSUE TITLE
Script run but nothing work in game

### ISSUE THREAD

**Issue by MrBuffett** [aRTy42/POE-ItemInfo#138]
I downloaded 2.16 and AHK 1.1.33. The scripts open check for updated and run in the system tray. I can open option but in the game, nothing pop up with any Macro. I tried in Windowed and Full screen windowed

**Comment by aRTy42** [comment]
I think you meant to go to the [PoE-TradeMacro](https://github.com/PoE-TradeMacro/POE-TradeMacro). This is just a smaller part of it and I don't maintain this project anymore. Unfortunately it looks like the TradeMacro is not getting updated anymore either.
