### ISSUE TITLE
Essence Tooltip Support

### ISSUE THREAD

**Issue by Eruyome** [aRTy42/POE-ItemInfo#16]
I'll leave this here as a note, maybe I'll implement it myself sometime, maybe someone will beat me to it.

Although I added an IsEssence check there is still no tooltip text for essences (stacksize, upgrades to/from, can be corrupted to/from).

**Comment by aRTy42** [comment]
Closing this. I don't think there is anything relevant to show on essences. If you could Ctrl+C the monster before opening for not having to remember the names of the purple essences, that would be nice little feature, but you can't.

Stacksize and upgrading is self-explanatory with minimal knowledge of essences.
