### ISSUE TITLE
1.1.7 issue

### ISSUE THREAD

**Issue by Artyfice** [aRTy42/POE-ItemInfo#21]
I was using 1.1.4 without any issue and I just upgraded to 1.1.7.

^d tooltip doesn't contain any sell, and ^q opens a webpage with this message "The browser (or proxy) sent a request that this server could not understand."

Am I doing it wrong or is the 1.1.7 broken?

**Comment by Eruyome** [comment]
First, you openend an issue on the wrong repository. This is PoE-ItemInfo, but you want https://github.com/PoE-TradeMacro/POE-TradeMacro.

Secondly, have you tried 1.1.7.1? Here's an issue for your problem https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/89
