### ISSUE TITLE
Currency calculation breaks on stacks with >= 1000 items

### ISSUE THREAD

**Issue by iulianov** [aRTy42/POE-ItemInfo#22]
The stack size uses spaces as the thousands separator and breaks the currency conversion code.
Sorry for not just issuing a pull request but the fix is to change:
`StackSize := StackSizeParts1`
to:
`StackSize := StrReplace(StackSizeParts1," ")`
on line 6042 (inside the first `Else` of `ConvertCurrency(ItemName, ItemStats)`)

**Comment by aRTy42** [comment]
Thanks.

I'm currently not doing much for the script, but I will include it when I find the time, along with other open issues.
