### ISSUE TITLE
Advanced search window problem

### ISSUE THREAD

**Issue by ricds** [aRTy42/POE-ItemInfo#23]
Hi, the advanced search is good when i first open the script. But after some uses (like 2-3 times) the windows just shrink and the affixes are not readable anymore Is this a problem with the script or something in my computer? Thanks.

(Hopefully) See image above:

![image](https://cloud.githubusercontent.com/assets/9935501/20426360/f860cae0-ad65-11e6-9d38-a48796f61677.png)

**Comment by Eruyome** [comment]
https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/93
Wrong Repository/Project.
