### ISSUE TITLE
Armory Map was renamed to Armoury Map

### ISSUE THREAD

**Issue by Eruyome** [aRTy42/POE-ItemInfo#25]

**Comment by aRTy42** [comment]
Renamed.

**Comment by jn64** [comment]
@aRTy42 Think there was a mistake. Was renamed to `Armoury` in 3daed50764ad6385ac1ff2c0a0bc52661e75a032 but then reverted to `Armory` in 891248d5b1910429104676181a318e0e434b4a6b.

**Comment by aRTy42** [comment]
Thanks for the report, I didn't fix all spots in the automated process back then, as it turns out. Made the changes now so it should be correct again with the next release (and this time stay this way).
