### ISSUE TITLE
show pseudo mods (e.g. total res)

### ISSUE THREAD

**Issue by mindyk** [aRTy42/POE-ItemInfo#29]
i would love to see total res on the item info popup.

**Comment by Eruyome** [comment]
If anyone is interested in imlpementing this, it should be possible to mostly copy and paste it from [PoE-TradeMacro](https://github.com/PoE-TradeMacro/POE-TradeMacro).

File: `trade_data/TradeMacro.ahk`
Function: `TradeFunc_PrepareNonUniqueItemMods`

Total resistances, total elemental resistances, total life and a lot of total dmg/spell dmg mods.

**Comment by Eruyome** [comment]
https://github.com/aRTy42/POE-ItemInfo/pull/30 Made a pull request.

**Comment by aRTy42** [comment]
Merged.
