### ISSUE TITLE
Stops working after a while and need to reload it

### ISSUE THREAD

**Issue by Rufus66** [aRTy42/POE-ItemInfo#3]
After a random amount of time when trying to press ctrl + c on an item, nothing will happen. I have to right click the icon in the task bar, the menu opens after around 5 seconds and i press reload and it starts working again. When this happens the pause key will not work either it's like the whole script has stopped. When it is working normally right clicking the icon the menu comes up instantly.

**Comment by aRTy42** [comment]
Unfortunately that is a rather unspecific issue. I can't tell if autohotkey itself has a problem, if it is about memory, if it is something in the script or something else entirely. Without being able to reproduce it or having multiple people with the issue who could narrow it down, I won't be able to fix that.
