### ISSUE TITLE
bug or error?

### ISSUE THREAD

**Issue by ghost** [aRTy42/POE-ItemInfo#33]
When starting this script - got an error like this: Call to nonexistent function
[http://imgur.com/a/K7V2u](url)

**Comment by aRTy42** [comment]
Get a recent autohotkey version at http://ahkscript.org/
If you are missing that function, you have a version from before March 28, 2015.

**Comment by aRTy42** [comment]
I'll assume that fixed it and close this issue. Please reopen if the problem remains.
