### ISSUE TITLE
ParseItemType failing for cerrtain items

### ISSUE THREAD

**Issue by Eruyome** [aRTy42/POE-ItemInfo#34]
https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/128 As descibed here the parsing fails in this case. 

```` 
Loop, Parse, ItemDataNamePlate, `n, `r
```` 
This loop returns after finding "cage" in the second line of the item name plate assuming the item is a helmet without checking the third line were it would find "map". Not sure what the best solution to solve this would be, yet.

**Comment by aRTy42** [comment]
How about strictly using the 3rd line for rares as we already do for uniques in the code lines directly below the quoted section. So we check RarityLevel > 2 instead of = 4. Like:

    ; Check name plate section
    Loop, Parse, ItemDataNamePlate, `n, `r
    {
        ; Get third line in case of rare or unique item and retrieve the base item name
        LoopField := RegExReplace(A_LoopField, "<<.*>>", "")
        If (RarityLevel > 2)
        {

**Comment by Eruyome** [comment]
Should work, at least I can't think of  a case where this does lead to issues right now, very tired though ;-)

**Comment by aRTy42** [comment]
Implemented the code in my 2.5.01 release. It works for the item example provided in your issue#128.
