### ISSUE TITLE
[BUG] Pseudo calculated for unique map

### ISSUE THREAD

**Issue by byg0n3** [aRTy42/POE-ItemInfo#35]
Subj
![map_pseudo](http://i.imgur.com/VD84zEW.png)

**Comment by aRTy42** [comment]
Did you use the script on another item shortly before the map that had +25% total ele res? It might be a case where the data was not properly reset.

**Comment by Eruyome** [comment]
That's very possible, I should have reset all data correctly on TradeMacro, not so sure about that on ItemInfo.

**Comment by aRTy42** [comment]
I can't reproduce it though.

dein0s, if you still have that map, does the pseudo mod always show up? In case it does not, can you remember what you did before or even manage to figure out a certain sequence that causes it?

**Comment by byg0n3** [comment]
Okay, right now it does not show up. It happened too late at night and before the patch, so I can not truly remember steps to reproduce it.
I'll try few things, but no promises here. Guess it was just temporary cache issue or smth like this.

**Comment by byg0n3** [comment]
Still randomly getting this 'pseudo' on different items, no exact steps to reproduce yet.
![gem_pseudo](http://i.imgur.com/DRWEoMh.png)
![helmet_pseudo](http://i.imgur.com/TutccvD.png)

**Comment by 4GForce** [comment]
I managed to reproduce it with the following : 
- use script on rare ring with implicit + x% some resist
- use script on a gem ( shows the pseudo + x% total Elemental Resistance )

Problem solved by resetting Item.Implicit in ParseItemData method ( Item.Implicit := "" )

**Comment by aRTy42** [comment]
Thank you. In hindsight that was a pretty stupid mistake to overlook since there was another issue with implicits before.

**Comment by 4GForce** [comment]
Btw, the Item class doesn't even initialize hasImplicit and Implicit attributes.
Building an Item.Reset() method might be the way to go, both for ParseItemData and the Item class constructor.

You guyz need a contributor ??  I'm trying to learn AutoHotKey while working on my c++ skills and my poe builds.  I have some spare time, let me know.

**Comment by aRTy42** [comment]
I am taking care of the script because no one else wanted to when the last person stepped down and I didn't want to see such a helpful tool become outdated. At the moment I am also mostly keeping it working than developing new things. The last few major functionality updates are all from Eruyome, because he is actively working on the TradeMacro.

If you want to contribute, please do.

**Comment by 4GForce** [comment]
Not sure how this is suppose to work but I can't send pull request.  I guess you need to add me to repo somehow.

**Comment by aRTy42** [comment]
You fork the repository, make changes to your copied version and then send a pull request.

**Comment by 4GForce** [comment]
Says I don't have authorization, pull request are working on my personal repo so it can't be network related.  But no stress, don't waste your Saturday night.

![pull request failed](https://cloud.githubusercontent.com/assets/25257792/22179232/d328a34a-e01b-11e6-882c-dbfa7e42835a.jpg)

**Comment by 4GForce** [comment]
nvm, I deleted everything and started over, now it works
