### ISSUE TITLE
Add option to change Pause keybind

### ISSUE THREAD

**Issue by Noshei** [aRTy42/POE-ItemInfo#36]
I use the pause key for push-to-talk, I have it rebound to a custom G key on my keyboard.  Unfortunately this causes this script to pause/unpause when I try to use push-to-talk.  I've been commenting out the line where pause is captured by the script to avoid conflicts, but this has to be redone every time I relaunch the script.

It would be great if you could add a way to change this keybind or simply remove it.

**Comment by Eruyome** [comment]
You know, couldn't you just use some other key than pause for push-to-talk, you have that bound to a second custom key anway?

This doesn't mean adding such an option is a bad thing, just saying.

**Comment by aRTy42** [comment]
I could move the pause bind into the AdditionalMacros.txt where it is easier accessible. Would that work for you?

**Comment by Noshei** [comment]
So long as I can edit it and not have it get reset every time I restart my computer, I'm happy with whatever works for you guys.

**Comment by aRTy42** [comment]
I moved the pause key bind line to the AdditionalMacros.txt file. I'm not at home for the next few days and I don't exactly want to put out a release again just for that now. You can just download the current GitHub version though, Noshei (tab "<>Code", green button "clone or download", download zip). That way you don't have to wait till next week and can also give feedback to whether it achieves what you wanted.

**Comment by Noshei** [comment]
That worked great, thanks.

**Comment by Eruyome** [comment]
@Noshei By the way, why would you have to redo the edit every time you restart your computer? Are you using Git to always download the newest files from the master branch overwriting the old files? Otherwise you would only have to change the script again after downloading a new release. Just curious.

**Comment by Noshei** [comment]
I think it was because I was editing main.ahk from TradeMacro.  I'm guessing this is created new every time you run Run_Only_This.ahk or Run_without_Admin_Elevation.ahk is ran.  I realized this when I was copying the changed aRTy42 made into the appropriate files.  That is also the file (main.ahk) you get sent to if you right click the taskbar icon and click Edit This Script.

**Comment by Eruyome** [comment]
Yeah that's right, some scripts are merged into main.ahk, changing anything there will be reset.

**Comment by aRTy42** [comment]
I included the change in the current release.
