### ISSUE TITLE
Its useless but its broken

### ISSUE THREAD

**Issue by 4GForce** [aRTy42/POE-ItemInfo#43]
Random find, easy fix.  I know the method is not used but it was still broken.

![adjustrangeforqualityfix](https://cloud.githubusercontent.com/assets/25257792/22171868/33cf1f0a-df66-11e6-9836-42e03ad52b83.jpg)

**Comment by aRTy42** [comment]
Thanks

**Comment by 4GForce** [comment]
Well, I realised that it was probably working anyway.  I'm new to AutoHotkey and I find it confusing with the mix of c++ and ahk.

The == operator seems to work in ahk scripts but only with parentheses

if 0             ; false  ( any language )
if 0 = 0        ; true ( ahk )
if 0 == 0     ; false ( ahk )
if ( 0 = 0 )    ; true ( ahk )
if ( 0 == 0 )  ; true ( c++, but also works in ahk scripts )

At least I'm learning,

4G

**Comment by aRTy42** [comment]
I was not aware of that either.

**Comment by Eruyome** [comment]
I'm easily confused with ahk comparisons, too...
The == operator behaves identically to = except when either of the inputs is not a number, in which case == is always case sensitive and = is always case insensitive.
Also == is only valid in an expression. In a traditional IF (no parentheses), the second = becomes part of the text to compare.
