### ISSUE TITLE
 Add mjolner legacy/non legacy not supported

### ISSUE THREAD

**Issue by JohnPrisoner** [aRTy42/POE-ItemInfo#5]
Rarity: Unique
Mjölner
## Gavel

One Handed Mace
Physical Damage: 76-139 (augmented)
Critical Strike Chance: 5.00%
## Attacks per Second: 1.15

Requirements:
Level: 60
Str: 412 (augmented) (unmet)
## 40% increased Stun Duration on Enemies

80% increased Physical Damage
Skills Chain +1 times
30% increased Lightning Damage with Weapons
+200 Strength Requirement
+300 Intelligence Requirement
## 30% chance to Cast Socketed Lightning Spells on Hit

Look the storm in the eye and you will have its respect.

**Comment by aRTy42** [comment]
Are you using the latest version of the script? The Umlaut got broken in a previous release but should be fine at the moment. If you are using the latest version, I have to look whether language settings are breaking it.

**Comment by JohnPrisoner** [comment]
Latest yeah 2.3.07, 

English lang, i check now from global links and find problems again with legacy/non-legacy mjolners.

"Unique item currently not supported"... all other items is fine.

![mjolner bug](https://cloud.githubusercontent.com/assets/3692810/18076267/0ab7fdc8-6e85-11e6-8423-0b74a593acac.png)

**Comment by aRTy42** [comment]
I could not reproduce the issue yet, the script works fine for ingame links for me. Also the clipboard data you posted at the start gets correctly parsed by the script when I tried it.

Could you take a look at the file "uniques.txt" in the data folder and Ctrl+F for "Mjölner" or just "mj" to see if your data file has a visible problem?

**Comment by JohnPrisoner** [comment]
Mj**ö**lner - in my uniques.txt  it is Mj**ц**lner. (Cyrilic windows users bug i think) I copy paste correct name and save as in Unicode.

Now working fine. But show old mjolner version 30% now correct 100%. I think this problem with cyrilic default language in windows 7. When  **ö** show as **ц** or with Default Windows 7 ANSI coding.

![mjolner bug](https://cloud.githubusercontent.com/assets/3692810/18231617/ab000984-72c6-11e6-9de0-bd168e5c1d67.png)

Fixed Unicode file:

[Uniques.txt](https://github.com/aRTy42/POE-ItemInfo/files/453961/Uniques.txt)

**Comment by aRTy42** [comment]
The script shows only the current version of uniques, it does not display legacy information yet.

**Comment by JohnPrisoner** [comment]
Previous 2.3 version Mjolner legacy 50% and non legacy 30%... 

So why now in 2.4 shows old 30%? (Previous screen link from 50% Mjolner legacy)
If in current 2.4 version now after rebalance all mjolners chance up to 100% Cast Socketed Lightning Spells on Hit after **divine**.

Current Mjolner version screen:
![mjolner bug](https://cloud.githubusercontent.com/assets/3692810/18250329/ab1cb104-738b-11e6-911a-67edeed08d88.png)

Rarity: Unique
<set:MS><set:M><set:S>Mjölner

## Gavel

One Handed Mace
Quality: +20% (augmented)
Physical Damage: 92-168 (augmented)
Critical Strike Chance: 5.00%

## Attacks per Second: 1.15

Requirements:
Level: 60
Str: 412 (augmented) (unmet)

## Int: 300 (augmented) (unmet)

## Sockets: R-B-B 

## Item Level: 69

## 40% increased Stun Duration on Enemies

98% increased Physical Damage
Skills Chain +1 times
35% increased Lightning Damage with Weapons
+200 Strength Requirement
+300 Intelligence Requirement

## Cast a Socketed Lightning Spell on Hit

Look the storm in the eye and you will have its respect.

**Comment by aRTy42** [comment]
All the unique data comes from the Uniques.txt file and that file was not updated for 2.4 yet. The script only looks up the name of the unique item and displays the stats saved in the file, so it still displays 30%.
