### ISSUE TITLE
Rename "Lib" folder to lower case

### ISSUE THREAD

**Issue by Eruyome** [aRTy42/POE-ItemInfo#50]
A while ago I renamed this folder (TradeMacro) to lowercase, someone complained about it. Now I have it lowercase on my repo but it's still uppercase on this repo, that's really annoying when I want to merge ItemInfo to TradeMacro... Could you change this please?

http://stackoverflow.com/questions/11183788/in-a-git-repository-how-to-properly-rename-a-directory

**Comment by Eruyome** [comment]
Well, could have done this myself .... https://github.com/aRTy42/POE-ItemInfo/pull/51

**Comment by aRTy42** [comment]
Merged
