### ISSUE TITLE
SettingsUI Controls overlapping

### ISSUE THREAD

**Issue by 4GForce** [aRTy42/POE-ItemInfo#52]
Mostly in the tooltip section, i'm working on it.

**Comment by 4GForce** [comment]
From what I've read this gui can be used within tabs, this would require testing if you can point me to that scenario. ( I use gui margin positionning in some cases )

Fixed
- using basic control sizes ( except for groupboxes and button/edit width )
- position all controls relative to previous ( avoiding absolute positionning as much as possible )
- using +m is limited to ahk [v1.1.16+] wich souldn't be a problem in our case
- limited most edit field to numbers
- centered the footer text and buttons

**Comment by 4GForce** [comment]
Well, I found out that the gui is used in a tab within TradeMacro and margin positionning breaks it.
I'll work on fixing this.

**Comment by Eruyome** [comment]
Yeah, the positioning is a bit complicated, I wasn't aware of any problems though the last time I worked on it to make it tab-compatible for TradeMacro.

**Comment by 4GForce** [comment]
-1 to ahk for form building
The problem might not appear to everyone due to screen res, windows theme, etc
But I clearly had overlapping controls in the tooltip section and I'll do my best to fix it but with stuff like groupboxes not even acting as container and more, I can't guarantee 100% quality on every systems.

**Comment by Eruyome** [comment]
Could you show me a screenshot of this mentioned overlapping?

**Comment by aRTy42** [comment]
I've reverted the merge. Could you two check if the current state of the repo is working for you regarding the encoding issues, please.

**Comment by Eruyome** [comment]
It seems to work. Both ItemInfo and TradeMacro.

Btw, I'll say it again, when merging PRs you should use `Squash and merge` instead of merge. Causes less clutter in the commit history ;-) Makes sense for normal commits too to squash a few together.

**Comment by aRTy42** [comment]
I misunderstood your squashing comment from last time, I thought that was only an option when using the desktop version or command line and I usually use the web version. I looked it up again and changed the setting for the repo to only allow squash-merge now, so I will remember next time.

**Comment by Eruyome** [comment]
Yeah, could have been a bit more clear with my explanation. I don't always use squash but at least when I have a few commits lined up from my dev branch and merge it to my master branch. Have only used it via the web ui myself.

I also try to squash only commits that are somewhat related or just minor things. Seperating bigger changes is probably a good idea.

**Comment by 4GForce** [comment]
New TradeMacro 1.7.2 release seems to be working fine.
And here are the screenshots of the UI, its minor but I felt like fixing it.

In the tooltip section

![iteminfosettingsui](https://cloud.githubusercontent.com/assets/25257792/22315193/5007b60c-e333-11e6-83be-1a82ebe8b83a.jpg)

In the hotkey section

![trademacrosettingsui](https://cloud.githubusercontent.com/assets/25257792/22315197/5860972e-e333-11e6-8f2b-bee4ef996169.jpg)

**Comment by 4GForce** [comment]
Quick fix, nothing fancy this time and I made sure  it was working with TradeMacro tab control.

![iteminfosettingsui_fixed](https://cloud.githubusercontent.com/assets/25257792/22318191/9e9f341c-e346-11e6-8160-4b052514fde6.jpg)

**Comment by Eruyome** [comment]
You can't really fix that overlapping in the TradeMacro Hotkey section, those checkboxes expect some text after the box and it doesn't seem like you can reduce the elements width to only have the size of the box. Therefore this invisible/non-existing text overlaps the border. I decided to just keep it that way.

**Comment by aRTy42** [comment]
You could move the text fields and checkboxes a little to the left. With GuiAddEdit x+5 and GuiAddCheckbox x+3 it works.

You could also make the text fields a bit smaller.

**Comment by 4GForce** [comment]
Well I still haven't figured out how to properly commit changes to TradeMacro branch but changing those editboxes from 'x+10' to 'x+1' sure solves the problem, from my perspective at least.

**Comment by Eruyome** [comment]
Is it so hard to properly commit to TradeMacro?^^

Fork the latest version, make some changes, push them cross-fork (pull request) while selecting the TradeMacro master branch as HEAD. 

Can't be any different then making changes and PRs to ItemInfo, or am I wrong?

**Comment by 4GForce** [comment]
Well, when I click fork from TradeMacro repo it brings me to my own ItemInfo repo fork https://github.com/4GForce/POE-ItemInfo ?!

I don't want to delete my ItemInfo fork because I have a pending pull request and from there I don't even see the TradeMacro files ... maybe I'm doing something wrong ?!?

**Comment by Eruyome** [comment]
Well, maybe its a bit more complicated since TradeMacro itself is a forked repo. Maybe I'll make a second github account and test it a bit.

**Comment by 4GForce** [comment]
I'll try deleting my ItemInfo fork once the pull request has passed and then fork directly from TradeMacro.

**Comment by Eruyome** [comment]
It seems the ItemInfo fork is a problem, worked with a new github account without any forks. There's probably a way to have both repos forked though.

**Comment by aRTy42** [comment]
merged your pull request, 4G
