### ISSUE TITLE
not working at all

### ISSUE THREAD

**Issue by wootlink** [aRTy42/POE-ItemInfo#6]
im using the newest version there is and it dosn't work at all i press ctrl+c and nothing happens
running the newest version of ahk. and windows 10

**Comment by aRTy42** [comment]
From the [forum thread](https://www.pathofexile.com/forum/view-thread/1678678)

> How To Use
> 1) Your game must be in "Windowed Fullscreen" or "Windowed" mode. Will not work in full screen.
> ...

Do you have one of these settings?

**Comment by wootlink** [comment]
solved apparently a nvidia update reset settings to fullscreen ty
