### ISSUE TITLE
error trying to run the script

### ISSUE THREAD

**Issue by aengis** [aRTy42/POE-ItemInfo#66]
![2017-02-15_142124](https://cloud.githubusercontent.com/assets/22846994/22976248/45db14be-f38a-11e6-80bb-46904e9e5bc1.png)

"unexpected message or incorrect format"

autohotkey version 1.1.24.05

**Comment by Eruyome** [comment]
Does this always happen?

**Comment by aengis** [comment]
yes, every time....

but the main script still runs ( didnt notice until today), and stays on the menu bar


win xp 32b sp3
no firewall
already tryed to add it to the anti viruts safe list, just in case... no changes.

**Comment by aRTy42** [comment]
I tried running the script in xp compatibility mode and also in 32 bit, but I can't reproduce the error.

Just to be sure (because of your file path): You unzipped the whole download and you are running the "POE-ItemInfo.ahk" file?

**Comment by aengis** [comment]
yes, i unzipped it and i am running the main script with right click run script

**Comment by Eruyome** [comment]
I'm a bit curious, do you also have this problem running TradeMacro https://github.com/PoE-TradeMacro/POE-TradeMacro/releases? You probably have but I want to make sure. 

EDIT: If that's the case you could edit TradeMacros config file `config_trade.ini`. You can't get the script started, so you probably can't use the settings menu, so do it manually. This file is being created in the main script root folder on scriptstart. There's the key/value pair `ShowUpdateNotifications = 1`, change it to `0` to skip the update check. ItemInfo simply uses a default of 1 here while TradeMacro actually can change this option. Of course you can also find the line `	ShowUpdateNotification := 1` in the ItemInfo code and change it to `0` to test it, but this isn't a long term solution.

There's probably something wrong with the WinHTTP request but I can't say yet what exactly, this may need giving you a a dev version with more debug output but I'm trying to release a TradeMacro 2.0 beta today so I'm a bit more focused to do that first.

If you have problems with all WinHTTP requests you can't use TradeMacro, you could use ItemInfo though as long as you skip the UpdateCheck.

**Comment by aengis** [comment]
yup, error, gonna try the fix 
![2017-02-19_143242](https://cloud.githubusercontent.com/assets/22846994/23102824/81626db0-f6b0-11e6-94ea-2451d30eb60a.png)
-------------------------------------------------

ok, the error on trademacro changed and got this.... i dont have any cookies on IE so it mighty be the reason.
![2](https://cloud.githubusercontent.com/assets/22846994/23102861/44731a7a-f6b1-11e6-9120-9aea916e0a3c.png)


the problem concerning itemInfo is not urgent since the script runs, even when it cant update himself.

**Comment by Eruyome** [comment]
It seems that you simply have problems with all WinHTTp requests, they all fail. WinHttp is used to download all kinds of information and the poe.trade pages. This is not cookie related.

**Comment by aengis** [comment]
![2017-02-20_112758](https://cloud.githubusercontent.com/assets/22846994/23121178/b6dbac72-f75f-11e6-88c6-356800086b78.png)

**Comment by Eruyome** [comment]
http://superuser.com/questions/558070/how-to-turn-off-winhttp-proxy

I really forgot about this... https://github.com/POE-TradeMacro/POE-TradeMacro/wiki/FAQ "2. Cloudflare Bypass (Cookies) issues": 

> **9.** TradeMacro uses [WinHTTPRequest 5.1](https://msdn.microsoft.com/de-de/library/windows/desktop/aa384106(v=vs.85).aspx) to connect to poe.trade/Github. WinHTTP has it's own [proxy settings](https://technet.microsoft.com/de-de/library/cc731131(v=ws.10).aspx), the default settings don't use any proxy server but this could have been changed on your system. You can check this by opening a [windows console window](http://www.howtogeek.com/235101/10-ways-to-open-the-command-prompt-in-windows-10/) and executing:   
`netsh winhttp show proxy`   
If this lists any proxy servers instead of "DirectAccess (no proxy server)" you can [reset this proxy](http://superuser.com/questions/558070/how-to-turn-off-winhttp-proxy).

According to this it is setup correctly. Not sure if that registry path is really missing...

**Comment by Eruyome** [comment]
You could download the latest code https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/devEru.zip and use `resources\tests\Test_WinHTTPRequest.ahk`. I added this to test download problems with some debug output, not sure if it helps. 

EDIT: Btw, I have that registry path and key.

**Comment by aengis** [comment]
cant turn off the winhttp since it seems i have none installed :P

**Comment by Eruyome** [comment]
Well, try to install (re-install) it then :p

**Comment by aengis** [comment]
i've been trying to find the package, but since there is no longer support for XP, the windowsxp-kb842773-v2-x86-esn ( winhttp 5.1 ) is impossible to find :(

**Comment by Eruyome** [comment]
Hm, that's too bad. At least ItemInfo is working for you when disabling updates. I should implement a fallback for all WinHTTP requests using UrlDownloadToFile if that fails. This would work for ItemInfo (always) and TradeMacro unless someday poe.trade has cloudflare protection again so that I have to send a useragent and cookies.
