### ISSUE TITLE
AHK Window zoom/scaling isssue?

### ISSUE THREAD

**Issue by planet37** [aRTy42/POE-ItemInfo#76]
Take a look at this screenshot. I can't tell where the issue is coming from. Standard win7 x64 w/ gtx1070
all scaling / zoom is off in os/gpu settings as far as i can tell. 

<a href="http://5cm.ru/view/i7/2JZ5.jpg" target="_blank"><img src="http://i7.5cm.ru/c/2JZ5.jpg" border="0"></a>

**Comment by Eruyome** [comment]
It seems like all font sizes are too big, everything else is fine.

**Comment by Eruyome** [comment]
Are you using any software that scales your windows font-sizes? For example https://support.microsoft.com/en-us/help/27928/windows-10-make-windows-easier-to-see
I know you said all zoom/scaling is off, but maybe there is something only font related that you missed.

**Comment by planet37** [comment]
i dont have any scaling/zoom features enabled and of course im playing in windowed / windowed fullscreen mode depening on what im doing. I can be using it fine for a few hours and then out of nowhere it starts happening. The loading messagebox is fine. 
![image](https://cloud.githubusercontent.com/assets/15804339/24582150/5baf6a84-16de-11e7-884d-fe7403bc150d.png)
double clicking the tray icon to open the settings and even "window spy" creates the bad windows
![image](https://cloud.githubusercontent.com/assets/15804339/24582166/c9fff742-16de-11e7-8596-11aa609c7bef.png)

It does seem like sometimes a reboot clears it but not always.

**Comment by byg0n3** [comment]
May I wonder what's your current DPI?

**Comment by Eruyome** [comment]
I'll close this for now, just reopen it if there are still issues.
