### ISSUE TITLE
meaning of "CP" and "CS"

### ISSUE THREAD

**Issue by DaveInDev** [aRTy42/POE-ItemInfo#87]
Hi,

I cannot find the info for the meaning of CP (prefix) and CS (suffix).
With such mods, it seems that an item can have up to 9 mods !!!!
Can someone explain ?

example here : 

Rarity: Rare
Foe Edge
Eye Gouger
--------
Claw
Physical Damage: 39-103 (augmented)
Elemental Damage: 1-3 (augmented)
Critical Strike Chance: 7.74% (augmented)
Attacks per Second: 1.50
Weapon Range: 9
--------
Requirements:
Level: 64
Dex: 113
Int: 113
--------
Sockets: R G 
--------
Item Level: 77
--------
+50 Life gained for each Enemy hit by Attacks
--------
51% increased Physical Damage CP
7% increased Elemental Damage with Weapons P
Adds 1 to 3 Cold Damage P
23% increased Critical Strike Chance S
+6 Mana gained on Kill S
+78 to Accuracy Rating CP
10% increased Accuracy Rating CS
15% increased Light Radius CS

**Comment by byg0n3** [comment]
Composite preffix and composite siffux accordingly.
`#% increased Energy Shield` is a preffix on ES armour and `#% increased Stun Recovery` is a suffix. But they can be combined into a single composite affix `#% increased Energy Shield / #% increased Stun Recovery` with lower values. Check http://poeaffix.net for more examples.

This issues is not related to the iteminfo script itself as this are the game terms.

**Comment by DaveInDev** [comment]
thank you for the clarification. So the 3+3 limit is still here :-)
