### ISSUE TITLE
+all resists missing in pseudo mods?

### ISSUE THREAD

**Issue by Nightblade** [aRTy42/POE-ItemInfo#89]
The ring in the attached screenshot has "+6% to all Elemental Resistances", however there's no line in the pseudo mods section that shows "+6% to Cold Resistance".

(The +6% IS correctly included in the pseudo mods for Fire and Lightning, and in the total.)

![image](https://cloud.githubusercontent.com/assets/23911/26272755/0218bd02-3d64-11e7-82fa-823e398f6783.png)

**Comment by Nightblade** [comment]
Hmmm I just noticed Cold Resist isn't shown on its own pseudo mod line on this ring either:

```
Beast Gyre
Two-Stone Ring
Item Level:    80
--------
Affixes (4):
   3 Prefixes
   1 Suffix
--------
+16% to Cold and Lightning Resistances
--------
27% increased Elemental…         21-30 (30)        5-42 (81)  T3 P 
+41 to maximum Mana              40-44 (35)       15-73 (81)  T7 P 
+5 to maximum Energy Shi…          4-8 (11)        1-47 (74) T10 P 
+44% to Lightning Resist…        42-45 (72)        6-48 (84)  T2 S
--------
(pseudo) +60% to Lightning Resistance
(pseudo) +76% total Elemental Resistance
```

**Comment by aRTy42** [comment]
Pseudo mods only show actual sums, they don't repeat a single entry. Both rings only have one line that gives cold res, so it is not mentioned. It used to be different quite a while ago and was changed to make the pseudo mod list shorter.

**Comment by Nightblade** [comment]
Ah ok.  Thanks for the info.
