### ISSUE TITLE
Map mod bug (avoid elemental ailments)

### ISSUE THREAD

**Issue by artofvs** [aRTy42/POE-ItemInfo#93]
http://i.imgur.com/eiWdc1q.png
Regexp should be
"Monsters have \d+% chance to Avoid Elemental Ailments"
instead of
"Monsters have \d+% chance to Avoid Elemental Status Ailments"

**Comment by aRTy42** [comment]
Thanks for the report. I already had that one fixed locally, but I didn't put a release out for it yet. The "...cause Elemental Ailments" mod was reworded in 3.0 aswell.
