### ISSUE TITLE
How Dumb Am I?

### ISSUE THREAD

**Issue by humenbean** [aRTy42/POE-ItemInfo#94]
Just started playing again after 6 months and when I installed everything from scratch, poe item info makes the default windows sound when I press ctrl+c to look at the item. What the heck did I do wrong? I never remembered it making noise.

Also, what happened to being able to click on items and have them pulled up in the wiki or poe.trade? I vaguely remember being able to do something like ctrl+s and it would pull it on on poe.trade or the ctrl+w wiki right away.

**Comment by aRTy42** [comment]
The trade functionalities come from the [TradeMacro](https://www.pathofexile.com/forum/view-thread/1757730). That one includes ItemInfo already. Download that one and tell me if there is still trouble.

**Comment by Eruyome** [comment]
Related https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/401
No idea so far except that it's something introduced by Windows 10 Creator Update (apparently).

Those functions should still be there, maybe  you used custom hotkeys that were being reset?

**Comment by aRTy42** [comment]
Closing this for now. If there are still issues, feel free to reopen it.
