### ISSUE TITLE
A request(Not sure where to put them.)

### ISSUE THREAD

**Issue by DaKingof** [aRTy42/POE-ItemInfo#95]
I think it would be nice if in the search feature popup it would show (if any) who has duplicate posts and how many of them they have. This would be helpful for a quick way to tell if the prices are being fixed. That way we could easily figure out if we should check poe.trade for more information.

**Comment by Eruyome** [comment]
Hey, not a bad idea, I may implement something like this in the future, have to rework something before being able to, which I planned to do anyway. Aside from that, this is the wrong repository ;-)
https://github.com/PoE-TradeMacro/POE-TradeMacro/issues That's the right one.

**Comment by aRTy42** [comment]
Copied to TradeMacro issue list, closing it here.
