### ISSUE TITLE
Problem with marble amulet

### ISSUE THREAD

**Issue by stevendza** [aRTy42/POE-ItemInfo#97]
There is an issue looking for the price of a marble amulet : https://pathofexile.gamepedia.com/Marble_Amulet

it searches for the unique version(Bloodgrip Marble Amule), not the base item.

**Comment by aRTy42** [comment]
Price searches are done by the [TradeMacro](/PoE-TradeMacro/POE-TradeMacro/issues).

I would guess that the script does search for the base item name, but the unique happens to be a lot cheaper than any normal/magic/rare marble amulets, so the unique gets listed first.
