### ISSUE TITLE
Unique flasks ItemData.Affixes populated incorrectly

### ISSUE THREAD

**Issue by philroberts** [aRTy42/POE-ItemInfo#99]
I believe unique flasks need GetNegativeAffixOffset to increment NegativeAffixOffset once for the flask text and once for the unique flavour text.

**Comment by aRTy42** [comment]
Fixed locally, will be pushed to GitHub soon.

**Comment by aRTy42** [comment]
Also tested it with the TradeMacro, Ctrl+Alt+D on Vinktar works now.
